FROM ubuntu:latest

WORKDIR /src

RUN apt-get update -y && DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential cmake wget git

RUN git clone https://github.com/google/googletest.git \
    && cd googletest && mkdir build && cd build && cmake .. && make && make install \
    && wget -qO- "https://sourceforge.net/projects/asio/files/asio/1.18.0%20%28Stable%29/asio-1.18.0.tar.gz" | tar xvz \
    && cd asio-1.18.0/include && rm Makefile* && cp -r * /usr/include/ \
    && rm -rf /src/*

CMD ["./build.sh", "dev"]
